import { Metadata } from 'next';
import Link from 'next/link';
import { Waves, ArrowLeft, Compass, ShieldAlert } from 'lucide-react';
import { MarineTidesDashboard } from '@/components/tools/MarineTidesDashboard';

export const metadata: Metadata = {
  title: 'Canada Marine Weather & Tide Tables | Live Bay of Fundy, Vancouver & Atlantic Tides',
  description:
    'Canadian Hydrographic Service (CHS) tide forecasts, high and low tide tables, Sea Surface Temperature (SST), ocean swell heights, and marine advisories for Bay of Fundy, Vancouver, Halifax, and Tofino.',
  keywords: [
    'Canada tide tables',
    'Bay of Fundy high tide time',
    'Vancouver tide chart',
    'Halifax marine weather swell',
    'Tofino surf tide forecast',
    'Canada ocean water temperature SST',
  ],
};

export default function MarineTidesPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Navigation Breadcrumb */}
        <div className="flex items-center gap-2 text-xs text-slate-400 font-semibold">
          <Link href="/" className="hover:text-cyan-400 transition-colors flex items-center gap-1">
            <ArrowLeft className="w-3.5 h-3.5" />
            Home
          </Link>
          <span>/</span>
          <Link href="/radar" className="hover:text-cyan-400 transition-colors">
            Marine &amp; Coastal
          </Link>
          <span>/</span>
          <span className="text-cyan-400">Coastal Marine &amp; Tide Tables</span>
        </div>

        {/* Hero Section */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-white/10 pb-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-black uppercase tracking-wider mb-3">
              <Waves className="w-3.5 h-3.5" />
              Canadian Hydrographic Service (CHS) Data
            </div>
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-white">
              Canadian <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-sky-300 to-indigo-400">Marine &amp; Tides</span>
            </h1>
            <p className="text-sm sm:text-base text-slate-300 max-w-3xl mt-2 leading-relaxed font-medium">
              Real-time coastal oceanography across Canada's Atlantic, Pacific, and Estuary waters.
              Explore semidiurnal tidal waveforms, high/low astronomical predictions, sea surface buoy temperatures, and ocean swell periods.
            </p>
          </div>

          <div className="flex items-center gap-3 shrink-0">
            <Link
              href="/tools/solunar"
              className="px-4 py-2.5 rounded-2xl bg-slate-900 hover:bg-slate-800 border border-white/10 text-xs font-bold text-slate-200 transition-all flex items-center gap-2 shadow-lg"
            >
              <Compass className="w-4 h-4 text-emerald-400" />
              <span>Solunar Fishing Chart</span>
            </Link>
          </div>
        </div>

        {/* Marine Interactive Dashboard */}
        <MarineTidesDashboard />

        {/* Oceanographic Science Highlights */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
          <div className="p-6 rounded-3xl bg-slate-900/60 border border-white/10 space-y-3">
            <div className="w-10 h-10 rounded-2xl bg-cyan-500/20 text-cyan-400 flex items-center justify-center font-bold text-lg">
              🌊
            </div>
            <h3 className="text-base font-bold text-white">Bay of Fundy Resonance</h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              The Bay of Fundy’s natural oscillation period (~12.5 hours) matches the Atlantic ocean’s tidal pulse, creating acoustic-like standing wave resonance with world-record vertical shifts exceeding 16 meters.
            </p>
          </div>

          <div className="p-6 rounded-3xl bg-slate-900/60 border border-white/10 space-y-3">
            <div className="w-10 h-10 rounded-2xl bg-sky-500/20 text-sky-400 flex items-center justify-center font-bold text-lg">
              🏄
            </div>
            <h3 className="text-base font-bold text-white">Pacific Swell Dynamics</h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              Groundswells reaching Vancouver Island and Tofino are generated by deep North Pacific low-pressure systems thousands of miles offshore, compressing kinetic wave energy as water shallows over continental shelf breaks.
            </p>
          </div>

          <div className="p-6 rounded-3xl bg-slate-900/60 border border-white/10 space-y-3">
            <div className="w-10 h-10 rounded-2xl bg-indigo-500/20 text-indigo-400 flex items-center justify-center font-bold text-lg">
              🌫️
            </div>
            <h3 className="text-base font-bold text-white">Atlantic Advection Fog</h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              Warm, moist tropical Atlantic air drifting northward over the cold southward-flowing Labrador Current rapidly condenses into dense marine sea fog blanketed across the Nova Scotia and Newfoundland coasts.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
